# Generated by Django 5.0.8 on 2024-08-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=20)),
                ('conpassword', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
