# Generated by Django 5.0.8 on 2024-08-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='conpassword',
        ),
    ]
