# Generated by Django 5.0.8 on 2024-08-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scc', '0003_admin_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/')),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('itchiness', models.CharField(max_length=3)),
                ('pain', models.CharField(max_length=3)),
                ('discharge', models.CharField(max_length=3)),
                ('predicted_disease', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
