# Generated by Django 5.0.8 on 2024-09-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scc', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrequest',
            name='remedies_and_medicines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
