# Generated by Django 5.0.8 on 2024-09-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scc', '0006_predictionrequest_remedies_and_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='scc.registration'),
        ),
    ]
