# Generated by Django 5.0.8 on 2024-09-05 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scc', '0007_predictionrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='scc.registration'),
        ),
    ]
